baseURL = "https://nicolasgreenwood.github.io"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    title = "Nicolas Greenwood"
    contentDir = "content/en"
    languageName = "English"
    weight = 1
    
    [[languages.en.menus.main]]
      name = "About"
      pageRef = "/about"
      weight = 10
    [[languages.en.menus.main]]
      name = "Contact"
      pageRef = "/contact"
      weight = 60
    [[languages.en.menus.main]]
      name = "Articles"
      pageRef = "/articles"
      weight = 40
    [[languages.en.menus.main]]
      name = "Poems"
      pageRef = "/poems"
      weight = 20
    [[languages.en.menus.main]]
      name = "Programming"
      pageRef = "/programming"
      weight = 30
    [[languages.en.menus.main]]
      name = "Misc"
      pageRef = "/misc"
      weight = 50

  [languages.sr-latn]
    title = "Nikolas Grinvud"
    contentDir = "content/sr-latn"
    languageName = "Srpski"
    weight = 2
    
    [[languages.sr-latn.menus.main]]
      name = "O meni"
      pageRef = "/about"
      weight = 10
    [[languages.sr-latn.menus.main]]
      name = "Kontakt"
      pageRef = "/contact"
      weight = 60
    [[languages.sr-latn.menus.main]]
      name = "Članci"
      pageRef = "/articles"
      weight = 40
    [[languages.sr-latn.menus.main]]
      name = "Pesme"
      pageRef = "/poems"
      weight = 20
    [[languages.sr-latn.menus.main]]
      name = "Programiranje"
      pageRef = "/programming"
      weight = 30
    [[languages.sr-latn.menus.main]]
      name = "Razno"
      pageRef = "/misc"
      weight = 50

  [languages.sr-cyrl]
    title = "Николас Гринвуд"
    contentDir = "content/sr-cyrl"
    languageName = "Српски"
    weight = 3
    
    [[languages.sr-cyrl.menus.main]]
      name = "О мени"
      pageRef = "/about"
      weight = 10
    [[languages.sr-cyrl.menus.main]]
      name = "Контакт"
      pageRef = "/contact"
      weight = 60
    [[languages.sr-cyrl.menus.main]]
      name = "Чланци"
      pageRef = "/articles"
      weight = 40
    [[languages.sr-cyrl.menus.main]]
      name = "Песме"
      pageRef = "/poems"
      weight = 20
    [[languages.sr-cyrl.menus.main]]
      name = "Програмирање"
      pageRef = "/programming"
      weight = 30
    [[languages.sr-cyrl.menus.main]]
      name = "Разно"
      pageRef = "/misc"
      weight = 50


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
  [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
      wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = "catppuccin-latte"
    noClasses = true